This is makeindex, version 2.15 [MiKTeX 2.9] (kpathsea + Thai support).
Scanning style file ./000-main.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file 000-main.acn....done (176 entries accepted, 0 rejected).
Sorting entries....done (1431 comparisons).
Generating output file 000-main.acr....done (116 lines written, 0 warnings).
Output written in 000-main.acr.
Transcript written in 000-main.alg.
